version: '3.5'

services:
  db_go_proj:
    restart: always
    container_name: db_go_wbtech
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=wbtech_db
    image: postgres:15.5-alpine3.18

  nats-streaming:
    image: nats-streaming:alpine3.18
    container_name: nats-streaming
    ports:
      - "4222:4222"
      - "8222:8222"
volumes:
  postgres_data:
  nats_storage: